### ISSUE TITLE
A !afk command

### ISSUE THREAD

**Issue by gfrewqpoiu** [gfrewqpoiu/MusicBot#11]
The !afk command would go through the queue and delete all Songs queued by the person that invoked it.

**Comment by estXcrew** [comment]
Idk how to implement this because I don't know how I could access the queue, but the basic idea that I'd do is use the AFK room for this. If user moves to the afk channel (or perhaps just leaves the music channel?), make the thing remove all the items from the playlist queued by that user.

**Comment by gfrewqpoiu** [comment]
Yeah same here. No idea how to implement this. But a !afk command would be sufficient.

**Comment by estXcrew** [comment]
I'll give it some thought tomorrow after I look at the whole bot script more closely and hopefully start to have an idea of what's what.

**Comment by gfrewqpoiu** [comment]
Following things need to be tested:
1. Does the queue order change for others?
2. What happens when multiple users have songs queued?
3. what if multiple people use afk at the same time?
4. What happens to the currently playing song?
5. Mods need a command to remove songs from other users.

**Comment by gfrewqpoiu** [comment]
is all working atm.
