### ISSUE TITLE
Deafened Users can skip even though they don't need to

### ISSUE THREAD

**Issue by V3NATOR** [gfrewqpoiu/MusicBot#8]
Deafening yourself and then using !skip will halfen the requirement to skip a song.

**Comment by gfrewqpoiu** [comment]
It will definitely reduce the number of skips required but not halve it, at least not when there are enough people in chat. But yeah deafened users shouldn't be able to skip

**Comment by gfrewqpoiu** [comment]
Fixed.

**Comment by gfrewqpoiu** [comment]
Closed
